### ISSUE TITLE
feature request: support for multiple databases

### ISSUE THREAD

**Issue by maxnotarangelo** [widefix/actual_db_schema#28]
This is a very cool gem, but since my app has multiple databases, I can't use it.

It's explicitly disallowed here:

https://github.com/widefix/actual_db_schema/blob/0ff50efd530795eddfc4dee1938c7f920acb3849/lib/tasks/db.rake#L80

Though it might be some work, in principle this feels doable to me. I'm happy to make an attempt at a PR.

**Comment by ka8725** [comment]
Thanks for the feedback! Please feel free to implement it.

**Comment by ka8725** [comment]
@maxnotarangelo how it's going? If you need some help please let me know. I'm going to refactor the code a bit to make this task a bit easier - https://github.com/widefix/actual_db_schema/pull/29/files

**Comment by rwehresmann** [comment]
@ka8725 I'd like to give it a try, however, I'm having issues adapting the `FakeApplication` to be a multi-db 😅 Do you have any gist on how could I do to adapt it?

**Comment by ka8725** [comment]
Closed by https://github.com/widefix/actual_db_schema/pull/56
