### ISSUE TITLE
Rollback phantom migrations manually rake task one by one

### ISSUE THREAD

**Issue by ka8725** [widefix/actual_db_schema#40]
I want to be able to roll back specific phantom migrations manually one by one from any branch that has the applied phantom migrations.

**Comment by VladislavSokov** [comment]
`rake db:rollback_branches` automatic rollback
`rake db:rollback_branches -manual` manually rollback one by one

manual mode should looks like this:
```
class AddNameToPosts < ActiveRecord::Migration[6.0]
  def change
    add_column :posts, :name, :string
  end
end
(1/1) Do you want rollback this migration? [y,n]
```
