### ISSUE TITLE
wrong location name for phatom migrations in README

### ISSUE THREAD

**Issue by 4tolexx** [widefix/actual_db_schema#43]
I am a user of this gem. I have spotted what I might call a typo in the README.

The README explains that the location for the phantom migrations is `tmp/migrations`. It's actually `tmp/migrated`. 

I made the above observation while testing out the library. I was looking for `tmp/migrations` but I didn't find it. Turns out that it was `tmp/migrated`.

we can also see that in the implementations here:

* https://github.com/widefix/actual_db_schema/blob/3b5c4ad36c8bd3e65a6e8247ab6ecc8a41b571a9/lib/actual_db_schema.rb#L31

I suppose it would be worthwhile to update the README to avoid confusion for other potential users.

**Comment by ka8725** [comment]
Fixed here - https://github.com/widefix/actual_db_schema/commit/d2f9912f373030de81992d4d9f0c81de2b224cdb

Thanks, @4tolexx for your contribution! Glad this gem helps you.

**Comment by 4tolexx** [comment]
:+1:
